### ISSUE TITLE
Error when using limit argument with method 'brute_force'

### ISSUE THREAD

**Issue by adrianhauber** [PEtab-dev/petab_select#3]
We (me + @fgwieland) encountered an error in PEtab-select with test case `0003` and using the limit argument (`5` in this case) in the CLI: 

    'Traceback (most recent call last):
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
         "__main__", mod_spec)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
         exec(code, run_globals)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\petab_select.exe\__main__.py", line 7, in <module>
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1137, in __call__
         return self.main(*args, **kwargs)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1062, in main
         rv = self.invoke(ctx)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1668, in invoke
         return _process_result(sub_ctx.command.invoke(sub_ctx))
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1404, in invoke
         return ctx.invoke(self.callback, **ctx.params)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 763, in invoke
         return __callback(*args, **kwargs)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\petab_select\cli.py", line 208, in candidates
         excluded_model_hashes=excluded_model_hashes,
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\petab_select\ui.py", line 79, in candidates
         problem.model_space.search(candidate_space, limit=limit)
       File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\petab_select\model_space.py", line 201, in search
         'An unknown error has occurred. Too many models were '
     ValueError: An unknown error has occurred. Too many models were generated. Requested limit: 5.0. Number of generated models: 18.
     '
It seems like petab-select fails when using brute_force with a limit unequal to the number of all possible models. Is this intended?

**Comment by fgwieland** [comment]
Our command line argument within the folder of case 0003 was:
    'petab_select candidates  -y petab_select_problem.yaml -s output\state.dill -o output\models.yaml --relative-paths  -l 5'

**Comment by dilpath** [comment]
Thanks for reporting! Should be fixed now.

NB: previously, the `limit` in the UI contradicted the docs for this argument.

Now, the behavior of `limit` matches the docs (i.e. it is a limit on the number of models in the output).

The previous behavior was a limit on the number of models sent to the candidate space at all (where models may be rejected by the candidate space and excluded from the output). This is now implemented as `limit_sent` in the Python and CLI UI.
`limit_sent` can result in no models in the output, if e.g. 5 models are sent to the candidate space, and all are rejected by the candidate space, the output will be an empty model list.
